select * from hr;

---Objective of study to find the reasons of attrition

--PRESENCE OF OVERTIME AND ATTRITION CORRELATION
SELECT OVERTIME, COUNT(*) AS TOTAL_EMPLOYEES
FROM hr
WHERE ATTRITION = 1
GROUP BY OVERTIME;

-- OVERALL GENDER DISTRIBUTION IN THE DATASET
SELECT GENDER, COUNT(*) AS TOTAL_EMPLOYEES FROM hr
GROUP BY GENDER;


-- RELATION BETWEEN PERFORMANCE RATING AND ATTRITION
SELECT PERFORMANCERATING, COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT
FROM HR
GROUP BY PerformanceRating;
-- THERE IS A NEGATIVE CORRELATION BETWEEN THE PERFORMACE RATING AND ATTRITION COUNT

-- RELATION BETWEEN THE PERCENT SALARY HIKE AND ATTRITION COUNT
SELECT PERCENTSALARYHIKE, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY  PercentSalaryHike
ORDER BY ATTRITION_COUNT DESC;
-- THERE IS A NEGATIVE CORRELATION BETWEEN THE PERCENT SALARY HIKE AND ATTRITION COUNT

-- DEPARTMENT WISE ATTRITION COUNT
SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1
GROUP BY Department
ORDER BY ATTRITION_COUNT DESC;
-- R&D AND SALES DEPARTMENT ARE HAVING THE MAX ATTRITION WITH ALMOST 95%

-- ENVIRONMENT SATISFACTION, JOB SATISFACTION AND RELATIONSHIP SATISFACTION ON ATTRITION COUNTS
SELECT ENVIRONMENTSATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY ENVIRONMENTSATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE ENVIRONMENT SATISFACTION AND ATTRITION COUNTS

SELECT JOBSATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY JOBSATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE JOB SATISFACTION AND ATTRITION COUNTS

SELECT RELATIONSHIPSATISFACTION, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY RELATIONSHIPSATISFACTION
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE RELATIONSIP SATISFACTION AND ATTRITION COUNTS


-- WORK LIFE BALANCE AND ATTRITION COUNTS
SELECT WORKLIFEBALANCE, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE Attrition = 1
GROUP BY WorkLifeBalance
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO RELATION BETWEEN THE WORK LIFE BALANCE AND ATTRITION COUNTS

-- DISTANCE FROM HOME AND ATTRITION COUNTS
select distancefromhome, count(*) as attr_count
from HR
where attrition = 1
group by distancefromhome
order by DistanceFromHome desc, attr_count desc;
-- THERE IS NO RELATION BETWEEN DISTANCE FROM HOME AND ATTRITION COUNTS


RENAME table attrition TO hr;



